### ISSUE TITLE
Add installation guide

### ISSUE THREAD

**Issue by tobloef** [dixonary/button-capture-reMarkable#8]
Could it be possible to add a quick installation guide to the README? Do you just run the project in QT Creator, or is there more to it? Thanks!

**Comment by dixonary** [comment]
Hi Tobias.

So the bad news is that I literally cannot remember how to install
button-capture. I think your intuition is correct - compiling and deploying
to the device with the standard qtcreator workflow should be sufficient. Could you confirm this for me if you get the chance?

The good news is we are *hopefully* going to have a better replacement for
all of the above in the near-ish future. Keep an eye out!

**Comment by tobloef** [comment]
Alright, thanks nonetheless. I'm currently trying to free up some space in the reMarkable root partition, as I currently only have 2 MB of the 5 MB required space available. If I figure it out and get to install button-capture, I will indeed let you know.

**Comment by dixonary** [comment]
We were taking a look at this before. There's a nodejs binary (14mb) which
could be symlinked into user space, among other things, to save space. (In
fact, that binary might not be used at all...)

Anyway, thanks and good luck :)

**Comment by tobloef** [comment]
So, I just straight up deleted that node binary, let's see if stuff breaks. I was then able to install button-capture-reMarkable by simply running the QT project as expected. Maybe no guide I needed then, that's up to you. Thanks for the help!

**Comment by dixonary** [comment]
Awesome! I'll leave the issue open because it would be nice for it to be
done eventually, but if the standard workflow exists now then that's great
:)

**Comment by spacekookie** [comment]
Can you package this project to be installable via `opkg`? I don't have a QT development set up and I don't really want to have to

**Comment by dixonary** [comment]
> Can you package this project to be installable via `opkg`? I don't have a QT development set up and I don't really want to have to

This can certainly be done, though the current version of draft, and button-capture, are effectively out of service at the moment [as I am completing my doctorate]. I would recommend using another launcher such as `oxide` which is actively maintained!
